// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package advanced_excel.actions;

import com.mendix.core.Core;
import com.mendix.logging.ILogNode;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import advanced_excel.proxies.DocumentType;
import advanced_excel.Utils;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.ss.util.CellReference;
import org.apache.poi.hssf.usermodel.HSSFCell;
import org.apache.poi.hssf.usermodel.HSSFRow;
import org.apache.poi.hssf.usermodel.HSSFName;
import org.apache.poi.hssf.usermodel.HSSFSheet;
import org.apache.poi.hssf.usermodel.HSSFWorkbook;
import org.apache.poi.xssf.usermodel.XSSFCell;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFName;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.apache.poi.xssf.usermodel.DefaultIndexedColorMap;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * Set a name for a cell
 */
public class Cell_SetName extends CustomJavaAction<java.lang.Boolean>
{
	private java.lang.String SheetName;
	private java.lang.Long Row;
	private java.lang.Long Column;
	private java.lang.String CellName;

	public Cell_SetName(IContext context, java.lang.String SheetName, java.lang.Long Row, java.lang.Long Column, java.lang.String CellName)
	{
		super(context);
		this.SheetName = SheetName;
		this.Row = Row;
		this.Column = Column;
		this.CellName = CellName;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		try
		{
			DocumentType docType = Utils.GetDocumentType();
			Workbook workbook = Utils.GetWorkBook();
			
			if (docType == DocumentType.XLS) {
				HSSFSheet sheet = ((HSSFWorkbook)workbook).getSheet(this.SheetName);
				if (sheet == null) { throw new Exception("Sheet: " + this.SheetName + " not found!"); }
				
				Integer rowNum = this.Row.intValue();
				Integer colNum = this.Column.intValue();
				
				HSSFRow row = sheet.getRow(rowNum);
				if (row == null) {
					row = sheet.createRow(rowNum);
				}
				HSSFCell cell = row.getCell(colNum);
				if (cell == null) {
					cell = row.createCell(colNum);
				}
				String Letter = CellReference.convertNumToColString(colNum);
				String formula = "'" + this.SheetName + "'!$" + Letter + "$" + (rowNum + 1);
				
				HSSFName name = ((HSSFWorkbook)workbook).createName();
				name.setNameName(CellName);
				name.setRefersToFormula(formula);
			} else {
				XSSFSheet sheet = ((XSSFWorkbook)workbook).getSheet(this.SheetName);
				if (sheet == null) { throw new Exception("Sheet: " + this.SheetName + " not found!"); }
				
				Integer rowNum = this.Row.intValue();
				Integer colNum = this.Column.intValue();
				
				XSSFRow row = sheet.getRow(rowNum);
				if (row == null) {
					row = sheet.createRow(rowNum);
				}
				XSSFCell cell = row.getCell(colNum);
				if (cell == null) {
					cell = row.createCell(colNum);
				}
				String Letter = CellReference.convertNumToColString(colNum);
				String formula = "'" + this.SheetName + "'!$" + Letter + "$" + (rowNum + 1);
				
				XSSFName name = ((XSSFWorkbook)workbook).createName();
				name.setNameName(CellName);
				name.setRefersToFormula(formula);
			}
			
			return true;
		} catch (Exception e) {
			logger.error("ERROR in Advanced_Excel.Cell_SetName: " + e.getMessage() + "\n" + e.toString(), e);
			return false;
		} 
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "Cell_SetName";
	}

	// BEGIN EXTRA CODE
	protected static ILogNode logger = Core.getLogger("Advanced_Excel");
	// END EXTRA CODE
}
