// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package advanced_excel.actions;

import com.mendix.core.Core;
import com.mendix.logging.ILogNode;
import java.io.IOException;
import advanced_excel.Utils;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * Get sheet name by index
 */
public class Worksheet_GetNameByIndex extends CustomJavaAction<java.lang.String>
{
	private java.lang.Long Index;

	public Worksheet_GetNameByIndex(IContext context, java.lang.Long Index)
	{
		super(context);
		this.Index = Index;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		try
		{
			Workbook workbook = Utils.GetWorkBook();
			Sheet sheet = workbook.getSheetAt(this.Index.intValue());
			if (sheet == null) { throw new Exception("Sheet in the index: " + this.Index + " not found!"); }
			
			return sheet.getSheetName();
		} catch (Exception e) {
			logger.error("ERROR in Advanced_Excel.Worksheet_GetNameByIndex: " + e.getMessage() + "\n" + e.toString(), e);
			return "";
		} 
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "Worksheet_GetNameByIndex";
	}

	// BEGIN EXTRA CODE
	protected static ILogNode logger = Core.getLogger("Advanced_Excel");
	// END EXTRA CODE
}
