// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package advanced_excel.actions;

import com.mendix.core.Core;
import com.mendix.logging.ILogNode;
import java.io.IOException;
import advanced_excel.Utils;
import org.apache.poi.ss.usermodel.Workbook;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * Rename a worksheet
 */
public class Worksheet_Rename extends CustomJavaAction<java.lang.Boolean>
{
	private java.lang.Long Index;
	private java.lang.String NewName;

	public Worksheet_Rename(IContext context, java.lang.Long Index, java.lang.String NewName)
	{
		super(context);
		this.Index = Index;
		this.NewName = NewName;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		try
		{
			Workbook workbook = Utils.GetWorkBook();
			workbook.setSheetName(this.Index.intValue(), this.NewName);
			
			return true;
		} catch (Exception e) {
			logger.error("ERROR in Advanced_Excel.Worksheet_Rename: " + e.getMessage() + "\n" + e.toString(), e);
			return false;
		} 
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "Worksheet_Rename";
	}

	// BEGIN EXTRA CODE
	protected static ILogNode logger = Core.getLogger("Advanced_Excel");
	// END EXTRA CODE
}
