// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package advanced_excel.actions;

import com.mendix.core.Core;
import com.mendix.logging.ILogNode;
import java.io.IOException;
import advanced_excel.proxies.DocumentType;
import advanced_excel.Utils;
import org.apache.poi.ss.util.CellRangeAddress;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.hssf.usermodel.HSSFCell;
import org.apache.poi.hssf.usermodel.HSSFRow;
import org.apache.poi.hssf.usermodel.HSSFCellStyle;
import org.apache.poi.hssf.usermodel.HSSFSheet;
import org.apache.poi.hssf.usermodel.HSSFWorkbook;
import org.apache.poi.xssf.usermodel.XSSFCell;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFCellStyle;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * Set style on a range of cells
 * example:
 * 
 *     0 1 2 3 4 5 6  
 * 0 | -  -  h h h -  - |   h = header
 * 1 | -  -  + + + -  - |   + = values
 * 2 | -  -  + + + -  - |   - = empty fields
 * 3 | -  -  + + + -  - |
 * 4 | -  -  -  -  -  -  - |
 * 
 * to set style for the values of this table, first row will be 1, last row: 3, first col: 2 and last col: 4
 */
public class Worksheet_SetStyleByRange extends CustomJavaAction<java.lang.Boolean>
{
	private java.lang.String SheetName;
	private java.lang.Long FirstRow;
	private java.lang.Long LastRow;
	private java.lang.Long FirstCol;
	private java.lang.Long LastCol;
	private IMendixObject __CellFormat;
	private advanced_excel.proxies.CellFormat CellFormat;

	public Worksheet_SetStyleByRange(IContext context, java.lang.String SheetName, java.lang.Long FirstRow, java.lang.Long LastRow, java.lang.Long FirstCol, java.lang.Long LastCol, IMendixObject CellFormat)
	{
		super(context);
		this.SheetName = SheetName;
		this.FirstRow = FirstRow;
		this.LastRow = LastRow;
		this.FirstCol = FirstCol;
		this.LastCol = LastCol;
		this.__CellFormat = CellFormat;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		this.CellFormat = __CellFormat == null ? null : advanced_excel.proxies.CellFormat.initialize(getContext(), __CellFormat);

		// BEGIN USER CODE
		try
		{
			DocumentType docType = Utils.GetDocumentType();
			Workbook workbook = Utils.GetWorkBook();
			
			if (docType == DocumentType.XLS) {
				HSSFSheet sheet = ((HSSFWorkbook)workbook).getSheet(this.SheetName);
				if (sheet == null) { throw new Exception("Sheet: " + this.SheetName + " not found!"); }
				
				for (int i = FirstRow.intValue(); i <= LastRow.intValue(); i++)
				{
					HSSFRow row = sheet.getRow(i);
					if (row == null) { row = sheet.createRow(i); }
					for (int j = FirstCol.intValue(); j <= LastCol.intValue(); j++)
					{
						HSSFCell cell = row.getCell(j);
						if (cell == null) { cell = row.createCell(j); }
						
						if (CellFormat.getCustomFormat() == null)
						{
							HSSFCellStyle cellStyle = cell.getCellStyle();
							if (cellStyle != null)
							{
								short format = cellStyle.getDataFormat();
								HSSFCellStyle style = ((HSSFWorkbook)workbook).createCellStyle();
								Utils.CreateStyle(workbook, style, this.CellFormat, docType);
								style.setDataFormat(format);
								cell.setCellStyle(style);
							}
						}
						else
						{
							HSSFCellStyle style = ((HSSFWorkbook)workbook).createCellStyle();
							Utils.CreateStyle(workbook, style, this.CellFormat, docType);
							cell.setCellStyle(style);
						}
					}
				}
			} else {
				XSSFSheet sheet = ((XSSFWorkbook)workbook).getSheet(this.SheetName);
				if (sheet == null) { throw new Exception("Sheet: " + this.SheetName + " not found!"); }
				
				for (int i = FirstRow.intValue(); i <= LastRow.intValue(); i++)
				{
					XSSFRow row = sheet.getRow(i);
					if (row == null) { row = sheet.createRow(i); }
					for (int j = FirstCol.intValue(); j <= LastCol.intValue(); j++)
					{
						XSSFCell cell = row.getCell(j);
						if (cell == null) { cell = row.createCell(j); }
						
						if (CellFormat.getCustomFormat() == null)
						{
							XSSFCellStyle cellStyle = cell.getCellStyle();
							if (cellStyle != null)
							{
								short format = cellStyle.getDataFormat();
								XSSFCellStyle style = ((XSSFWorkbook)workbook).createCellStyle();
								Utils.CreateStyle(workbook, style, this.CellFormat, docType);
								style.setDataFormat(format);
								cell.setCellStyle(style);
							}
						}
						else
						{
							XSSFCellStyle style = ((XSSFWorkbook)workbook).createCellStyle();
							Utils.CreateStyle(workbook, style, this.CellFormat, docType);
							cell.setCellStyle(style);
						}
					}
				}
			}
			
			return true;
		} catch (Exception e) {
			logger.error("ERROR in Advanced_Excel.Worksheet_SetAutoFilter: " + e.getMessage() + "\n" + e.toString(), e);
			return false;
		} 
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "Worksheet_SetStyleByRange";
	}

	// BEGIN EXTRA CODE
	protected static ILogNode logger = Core.getLogger("Advanced_Excel");
	// END EXTRA CODE
}
